# -*- coding: utf-8 -*-
"""Project: 2 Guess The Number Game Python Project(computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptWElLHeVJ-cmP-53BjlLKHg0WwGMn0N
"""

#Guess The Number Game Python Project (Computer)

import random

secret_number = random .randint(1,100)
print("I have thought of a number between 1 and 100, can you please guess it?")

while True:
  guess =  int(input("enter your guess:"))
  if guess < secret_number:
    print("guess higher!")
  elif guess > secret_number:
   print("guess lower!")
  else:
   print("Congratulations! You guessed it right!")
   break #end the game.

